# Generated by Django 2.2.10 on 2020-07-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('facebook', 'fa-facebook'), ('instagram', 'fa-instagram'), ('google-plus', 'fa-google-plus'), ('linkedin', 'fa-linkedin-in')], max_length=20),
        ),
    ]
