# Generated by Django 2.2.10 on 2020-07-19 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200716_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='prenom',
            new_name='website',
        ),
    ]
