# Generated by Django 2.2.10 on 2020-07-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200719_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
