# Generated by Django 2.2.10 on 2020-07-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200719_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
